"""initial migration

Revision ID: 7414211261c5
Revises: 
Create Date: 2024-06-27 13:55:35.577339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7414211261c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('name', name=op.f('uq_campaigns_name'))
    )
    op.create_table('ener_end_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ener_end_uses')),
    sa.UniqueConstraint('name', name=op.f('uq_ener_end_uses_name'))
    )
    op.create_table('ener_prod_techs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ener_prod_techs')),
    sa.UniqueConstraint('name', name=op.f('uq_ener_prod_techs_name'))
    )
    op.create_table('energies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_energies')),
    sa.UniqueConstraint('name', name=op.f('uq_energies_name'))
    )
    op.create_table('event_categs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_categs')),
    sa.UniqueConstraint('name', name=op.f('uq_event_categs_name'))
    )
    op.create_table('struct_elem_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('value_type', sa.Enum('integer', 'float', 'boolean', 'string', name='propertytype'), nullable=False),
    sa.Column('unit_symbol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_struct_elem_props')),
    sa.UniqueConstraint('name', name=op.f('uq_struct_elem_props_name'))
    )
    op.create_table('ts_data_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_data_states')),
    sa.UniqueConstraint('name', name=op.f('uq_ts_data_states_name'))
    )
    op.create_table('ts_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('value_type', sa.Enum('integer', 'float', 'boolean', 'string', name='propertytype'), nullable=False),
    sa.Column('unit_symbol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_props')),
    sa.UniqueConstraint('name', name=op.f('uq_ts_props_name'))
    )
    op.create_table('u_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_u_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_u_groups_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('_is_admin', sa.Boolean(), nullable=False),
    sa.Column('_is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('building_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('struct_elem_prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['struct_elem_prop_id'], ['struct_elem_props.id'], name=op.f('fk_building_props_struct_elem_prop_id_struct_elem_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_building_props')),
    sa.UniqueConstraint('struct_elem_prop_id', name=op.f('uq_building_props_struct_elem_prop_id'))
    )
    op.create_table('c_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_c_scopes_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_c_scopes')),
    sa.UniqueConstraint('campaign_id', 'name', name=op.f('uq_c_scopes_campaign_id'))
    )
    op.create_table('event_categs_by_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('notification_level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='eventlevelenum'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['event_categs.id'], name=op.f('fk_event_categs_by_users_category_id_event_categs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_categs_by_users_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_categs_by_users')),
    sa.UniqueConstraint('user_id', 'category_id', name=op.f('uq_event_categs_by_users_user_id'))
    )
    op.create_table('site_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('struct_elem_prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['struct_elem_prop_id'], ['struct_elem_props.id'], name=op.f('fk_site_props_struct_elem_prop_id_struct_elem_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_props')),
    sa.UniqueConstraint('struct_elem_prop_id', name=op.f('uq_site_props_struct_elem_prop_id'))
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ifc_id', sa.String(length=22), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_sites_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('campaign_id', 'name', name=op.f('uq_sites_campaign_id'))
    )
    op.create_table('space_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('struct_elem_prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['struct_elem_prop_id'], ['struct_elem_props.id'], name=op.f('fk_space_props_struct_elem_prop_id_struct_elem_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space_props')),
    sa.UniqueConstraint('struct_elem_prop_id', name=op.f('uq_space_props_struct_elem_prop_id'))
    )
    op.create_table('st_check_missing_by_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_st_check_missing_by_campaigns_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_st_check_missing_by_campaigns')),
    sa.UniqueConstraint('campaign_id', name=op.f('uq_st_check_missing_by_campaigns_campaign_id'))
    )
    op.create_table('st_check_outliers_by_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_st_check_outliers_by_campaigns_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_st_check_outliers_by_campaigns')),
    sa.UniqueConstraint('campaign_id', name=op.f('uq_st_check_outliers_by_campaigns_campaign_id'))
    )
    op.create_table('st_cleanups_by_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_st_cleanups_by_campaigns_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_st_cleanups_by_campaigns')),
    sa.UniqueConstraint('campaign_id', name=op.f('uq_st_cleanups_by_campaigns_campaign_id'))
    )
    op.create_table('storey_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('struct_elem_prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['struct_elem_prop_id'], ['struct_elem_props.id'], name=op.f('fk_storey_props_struct_elem_prop_id_struct_elem_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storey_props')),
    sa.UniqueConstraint('struct_elem_prop_id', name=op.f('uq_storey_props_struct_elem_prop_id'))
    )
    op.create_table('u_groups_by_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_u_groups_by_campaigns_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['user_group_id'], ['u_groups.id'], name=op.f('fk_u_groups_by_campaigns_user_group_id_u_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_u_groups_by_campaigns')),
    sa.UniqueConstraint('campaign_id', 'user_group_id', name=op.f('uq_u_groups_by_campaigns_campaign_id'))
    )
    op.create_table('users_by_u_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_group_id'], ['u_groups.id'], name=op.f('fk_users_by_u_groups_user_group_id_u_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_by_u_groups_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_by_u_groups')),
    sa.UniqueConstraint('user_id', 'user_group_id', name=op.f('uq_users_by_u_groups_user_id'))
    )
    op.create_table('zone_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('struct_elem_prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['struct_elem_prop_id'], ['struct_elem_props.id'], name=op.f('fk_zone_props_struct_elem_prop_id_struct_elem_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_props')),
    sa.UniqueConstraint('struct_elem_prop_id', name=op.f('uq_zone_props_struct_elem_prop_id'))
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ifc_id', sa.String(length=22), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_zones_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('campaign_id', 'name', name=op.f('uq_zones_campaign_id'))
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ifc_id', sa.String(length=22), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_buildings_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings')),
    sa.UniqueConstraint('site_id', 'name', name=op.f('uq_buildings_site_id'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_scope_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='eventlevelenum'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_scope_id'], ['c_scopes.id'], name=op.f('fk_events_campaign_scope_id_c_scopes')),
    sa.ForeignKeyConstraint(['category_id'], ['event_categs.id'], name=op.f('fk_events_category_id_event_categs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('site_prop_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_prop_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_prop_data_site_id_sites')),
    sa.ForeignKeyConstraint(['site_prop_id'], ['site_props.id'], name=op.f('fk_site_prop_data_site_prop_id_site_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_prop_data')),
    sa.UniqueConstraint('site_id', 'site_prop_id', name=op.f('uq_site_prop_data_site_id'))
    )
    op.create_table('st_dl_weather_data_by_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_st_dl_weather_data_by_site_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_st_dl_weather_data_by_site')),
    sa.UniqueConstraint('site_id', name=op.f('uq_st_dl_weather_data_by_site_site_id'))
    )
    op.create_table('st_dl_weather_fcast_data_by_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_st_dl_weather_fcast_data_by_site_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_st_dl_weather_fcast_data_by_site')),
    sa.UniqueConstraint('site_id', name=op.f('uq_st_dl_weather_fcast_data_by_site_site_id'))
    )
    op.create_table('timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('unit_symbol', sa.String(length=20), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_timeseries_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['campaign_scope_id'], ['c_scopes.id'], name=op.f('fk_timeseries_campaign_scope_id_c_scopes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeseries')),
    sa.UniqueConstraint('campaign_id', 'name', name=op.f('uq_timeseries_campaign_id'))
    )
    op.create_table('u_groups_by_c_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_scope_id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_scope_id'], ['c_scopes.id'], name=op.f('fk_u_groups_by_c_scopes_campaign_scope_id_c_scopes')),
    sa.ForeignKeyConstraint(['user_group_id'], ['u_groups.id'], name=op.f('fk_u_groups_by_c_scopes_user_group_id_u_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_u_groups_by_c_scopes')),
    sa.UniqueConstraint('campaign_scope_id', 'user_group_id', name=op.f('uq_u_groups_by_c_scopes_campaign_scope_id'))
    )
    op.create_table('zone_prop_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_prop_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_zone_prop_data_zone_id_zones')),
    sa.ForeignKeyConstraint(['zone_prop_id'], ['zone_props.id'], name=op.f('fk_zone_prop_data_zone_prop_id_zone_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_prop_data')),
    sa.UniqueConstraint('zone_id', 'zone_prop_id', name=op.f('uq_zone_prop_data_zone_id'))
    )
    op.create_table('building_prop_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('building_prop_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_building_prop_data_building_id_buildings')),
    sa.ForeignKeyConstraint(['building_prop_id'], ['building_props.id'], name=op.f('fk_building_prop_data_building_prop_id_building_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_building_prop_data')),
    sa.UniqueConstraint('building_id', 'building_prop_id', name=op.f('uq_building_prop_data_building_id'))
    )
    op.create_table('ener_cons_ts_by_building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('energy_id', sa.Integer(), nullable=False),
    sa.Column('end_use_id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_ener_cons_ts_by_building_building_id_buildings')),
    sa.ForeignKeyConstraint(['end_use_id'], ['ener_end_uses.id'], name=op.f('fk_ener_cons_ts_by_building_end_use_id_ener_end_uses')),
    sa.ForeignKeyConstraint(['energy_id'], ['energies.id'], name=op.f('fk_ener_cons_ts_by_building_energy_id_energies')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ener_cons_ts_by_building_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ener_cons_ts_by_building')),
    sa.UniqueConstraint('building_id', 'energy_id', 'end_use_id', name=op.f('uq_ener_cons_ts_by_building_building_id'))
    )
    op.create_table('ener_cons_ts_by_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('energy_id', sa.Integer(), nullable=False),
    sa.Column('end_use_id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['end_use_id'], ['ener_end_uses.id'], name=op.f('fk_ener_cons_ts_by_site_end_use_id_ener_end_uses')),
    sa.ForeignKeyConstraint(['energy_id'], ['energies.id'], name=op.f('fk_ener_cons_ts_by_site_energy_id_energies')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_ener_cons_ts_by_site_site_id_sites')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ener_cons_ts_by_site_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ener_cons_ts_by_site')),
    sa.UniqueConstraint('site_id', 'energy_id', 'end_use_id', name=op.f('uq_ener_cons_ts_by_site_site_id'))
    )
    op.create_table('ener_prod_ts_by_building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('energy_id', sa.Integer(), nullable=False),
    sa.Column('prod_tech_id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_ener_prod_ts_by_building_building_id_buildings')),
    sa.ForeignKeyConstraint(['energy_id'], ['energies.id'], name=op.f('fk_ener_prod_ts_by_building_energy_id_energies')),
    sa.ForeignKeyConstraint(['prod_tech_id'], ['ener_prod_techs.id'], name=op.f('fk_ener_prod_ts_by_building_prod_tech_id_ener_prod_techs')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ener_prod_ts_by_building_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ener_prod_ts_by_building')),
    sa.UniqueConstraint('building_id', 'energy_id', 'prod_tech_id', name=op.f('uq_ener_prod_ts_by_building_building_id'))
    )
    op.create_table('ener_prod_ts_by_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('energy_id', sa.Integer(), nullable=False),
    sa.Column('prod_tech_id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['energy_id'], ['energies.id'], name=op.f('fk_ener_prod_ts_by_site_energy_id_energies')),
    sa.ForeignKeyConstraint(['prod_tech_id'], ['ener_prod_techs.id'], name=op.f('fk_ener_prod_ts_by_site_prod_tech_id_ener_prod_techs')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_ener_prod_ts_by_site_site_id_sites')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ener_prod_ts_by_site_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ener_prod_ts_by_site')),
    sa.UniqueConstraint('site_id', 'energy_id', 'prod_tech_id', name=op.f('uq_ener_prod_ts_by_site_site_id'))
    )
    op.create_table('events_by_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_events_by_buildings_building_id_buildings')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_events_by_buildings_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events_by_buildings')),
    sa.UniqueConstraint('building_id', 'event_id', name=op.f('uq_events_by_buildings_building_id'))
    )
    op.create_table('events_by_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_events_by_sites_event_id_events')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_events_by_sites_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events_by_sites')),
    sa.UniqueConstraint('site_id', 'event_id', name=op.f('uq_events_by_sites_site_id'))
    )
    op.create_table('events_by_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_events_by_zones_event_id_events')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_events_by_zones_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events_by_zones')),
    sa.UniqueConstraint('zone_id', 'event_id', name=op.f('uq_events_by_zones_zone_id'))
    )
    op.create_table('notifs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notifs_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifs'))
    )
    op.create_table('st_cleanups_by_ts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('last_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_st_cleanups_by_ts_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_st_cleanups_by_ts')),
    sa.UniqueConstraint('timeseries_id', name=op.f('uq_st_cleanups_by_ts_timeseries_id'))
    )
    op.create_table('storeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ifc_id', sa.String(length=22), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_storeys_building_id_buildings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storeys')),
    sa.UniqueConstraint('building_id', 'name', name=op.f('uq_storeys_building_id'))
    )
    op.create_table('ts_by_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_ts_by_buildings_building_id_buildings')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ts_by_buildings_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_by_buildings')),
    sa.UniqueConstraint('building_id', 'timeseries_id', name=op.f('uq_ts_by_buildings_building_id'))
    )
    op.create_table('ts_by_data_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('data_state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_state_id'], ['ts_data_states.id'], name=op.f('fk_ts_by_data_states_data_state_id_ts_data_states')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ts_by_data_states_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_by_data_states')),
    sa.UniqueConstraint('timeseries_id', 'data_state_id', name=op.f('uq_ts_by_data_states_timeseries_id'))
    )
    op.create_table('ts_by_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ts_by_events_event_id_events')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ts_by_events_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_by_events')),
    sa.UniqueConstraint('event_id', 'timeseries_id', name=op.f('uq_ts_by_events_event_id'))
    )
    op.create_table('ts_by_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_ts_by_sites_site_id_sites')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ts_by_sites_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_by_sites')),
    sa.UniqueConstraint('site_id', 'timeseries_id', name=op.f('uq_ts_by_sites_site_id'))
    )
    op.create_table('ts_by_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ts_by_zones_timeseries_id_timeseries')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_ts_by_zones_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_by_zones')),
    sa.UniqueConstraint('zone_id', 'timeseries_id', name=op.f('uq_ts_by_zones_zone_id'))
    )
    op.create_table('ts_prop_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['ts_props.id'], name=op.f('fk_ts_prop_data_property_id_ts_props')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ts_prop_data_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_prop_data')),
    sa.UniqueConstraint('timeseries_id', 'property_id', name=op.f('uq_ts_prop_data_timeseries_id'))
    )
    op.create_table('weather_ts_by_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.Enum('AIR_TEMPERATURE', 'DEWPOINT_TEMPERATURE', 'WETBULB_TEMPERATURE', 'WIND_SPEED', 'WIND_DIRECTION', 'SURFACE_SOLAR_RADIATION', 'SURFACE_DIRECT_SOLAR_RADIATION', 'SURFACE_DIFFUSE_SOLAR_RADIATION', 'DIRECT_NORMAL_SOLAR_RADIATION', 'RELATIVE_HUMIDITY', 'SURFACE_PRESSURE', 'TOTAL_PRECIPITATION', name='weatherparameterenum'), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('forecast', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_weather_ts_by_site_site_id_sites')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_weather_ts_by_site_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_ts_by_site')),
    sa.UniqueConstraint('site_id', 'parameter', 'forecast', name=op.f('uq_weather_ts_by_site_site_id'))
    )
    op.create_table('events_by_storeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('storey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_events_by_storeys_event_id_events')),
    sa.ForeignKeyConstraint(['storey_id'], ['storeys.id'], name=op.f('fk_events_by_storeys_storey_id_storeys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events_by_storeys')),
    sa.UniqueConstraint('storey_id', 'event_id', name=op.f('uq_events_by_storeys_storey_id'))
    )
    op.create_table('spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ifc_id', sa.String(length=22), nullable=True),
    sa.Column('storey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storey_id'], ['storeys.id'], name=op.f('fk_spaces_storey_id_storeys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaces')),
    sa.UniqueConstraint('storey_id', 'name', name=op.f('uq_spaces_storey_id'))
    )
    op.create_table('storey_prop_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storey_id', sa.Integer(), nullable=False),
    sa.Column('storey_prop_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['storey_id'], ['storeys.id'], name=op.f('fk_storey_prop_data_storey_id_storeys')),
    sa.ForeignKeyConstraint(['storey_prop_id'], ['storey_props.id'], name=op.f('fk_storey_prop_data_storey_prop_id_storey_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storey_prop_data')),
    sa.UniqueConstraint('storey_id', 'storey_prop_id', name=op.f('uq_storey_prop_data_storey_id'))
    )
    op.create_table('ts_by_storeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('storey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storey_id'], ['storeys.id'], name=op.f('fk_ts_by_storeys_storey_id_storeys')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ts_by_storeys_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_by_storeys')),
    sa.UniqueConstraint('storey_id', 'timeseries_id', name=op.f('uq_ts_by_storeys_storey_id'))
    )
    op.create_table('ts_data',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_by_data_state_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ts_by_data_state_id'], ['ts_by_data_states.id'], name=op.f('fk_ts_data_ts_by_data_state_id_ts_by_data_states')),
    sa.PrimaryKeyConstraint('ts_by_data_state_id', 'timestamp', name=op.f('pk_ts_data'))
    )
    op.create_table('events_by_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_events_by_spaces_event_id_events')),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_events_by_spaces_space_id_spaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events_by_spaces')),
    sa.UniqueConstraint('space_id', 'event_id', name=op.f('uq_events_by_spaces_space_id'))
    )
    op.create_table('space_prop_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('space_prop_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_space_prop_data_space_id_spaces')),
    sa.ForeignKeyConstraint(['space_prop_id'], ['space_props.id'], name=op.f('fk_space_prop_data_space_prop_id_space_props')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space_prop_data')),
    sa.UniqueConstraint('space_id', 'space_prop_id', name=op.f('uq_space_prop_data_space_id'))
    )
    op.create_table('ts_by_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_ts_by_spaces_space_id_spaces')),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name=op.f('fk_ts_by_spaces_timeseries_id_timeseries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ts_by_spaces')),
    sa.UniqueConstraint('space_id', 'timeseries_id', name=op.f('uq_ts_by_spaces_space_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ts_by_spaces')
    op.drop_table('space_prop_data')
    op.drop_table('events_by_spaces')
    op.drop_table('ts_data')
    op.drop_table('ts_by_storeys')
    op.drop_table('storey_prop_data')
    op.drop_table('spaces')
    op.drop_table('events_by_storeys')
    op.drop_table('weather_ts_by_site')
    op.drop_table('ts_prop_data')
    op.drop_table('ts_by_zones')
    op.drop_table('ts_by_sites')
    op.drop_table('ts_by_events')
    op.drop_table('ts_by_data_states')
    op.drop_table('ts_by_buildings')
    op.drop_table('storeys')
    op.drop_table('st_cleanups_by_ts')
    op.drop_table('notifs')
    op.drop_table('events_by_zones')
    op.drop_table('events_by_sites')
    op.drop_table('events_by_buildings')
    op.drop_table('ener_prod_ts_by_site')
    op.drop_table('ener_prod_ts_by_building')
    op.drop_table('ener_cons_ts_by_site')
    op.drop_table('ener_cons_ts_by_building')
    op.drop_table('building_prop_data')
    op.drop_table('zone_prop_data')
    op.drop_table('u_groups_by_c_scopes')
    op.drop_table('timeseries')
    op.drop_table('st_dl_weather_fcast_data_by_site')
    op.drop_table('st_dl_weather_data_by_site')
    op.drop_table('site_prop_data')
    op.drop_table('events')
    op.drop_table('buildings')
    op.drop_table('zones')
    op.drop_table('zone_props')
    op.drop_table('users_by_u_groups')
    op.drop_table('u_groups_by_campaigns')
    op.drop_table('storey_props')
    op.drop_table('st_cleanups_by_campaigns')
    op.drop_table('st_check_outliers_by_campaigns')
    op.drop_table('st_check_missing_by_campaigns')
    op.drop_table('space_props')
    op.drop_table('sites')
    op.drop_table('site_props')
    op.drop_table('event_categs_by_users')
    op.drop_table('c_scopes')
    op.drop_table('building_props')
    op.drop_table('users')
    op.drop_table('u_groups')
    op.drop_table('ts_props')
    op.drop_table('ts_data_states')
    op.drop_table('struct_elem_props')
    op.drop_table('event_categs')
    op.drop_table('energies')
    op.drop_table('ener_prod_techs')
    op.drop_table('ener_end_uses')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
