"""convert token_expiry field to datetime field

Revision ID: c14d2c20276b
Revises: 9b26504068a6
Create Date: 2024-06-28 14:32:04.294022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14d2c20276b'
down_revision: Union[str, None] = '9b26504068a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('authenticationtoken')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authenticationtoken',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('token_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='authenticationtoken_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='authenticationtoken_pkey')
    )
    # ### end Alembic commands ###
